config/routes.rb
Rails.application.routes.draw do

  root 'jobs#index'

  resources :jobs

end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :company_name, :job_title, :salary_range, :benefits, :description, :location, :requirements, :to_apply, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all.order("updated_at")
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to :root, notice: "Job successfully added."
    else
      render :new
    end
  end

  def show
    @job = Job.find_by_id(params["id"])
  end

  def edit
    @job = Job.find_by_id(params["id"])
  end

  def update
    @job = Job.find_by_id(params["id"])

    if @job.update_attributes(job_params)
      redirect_to @job, notice: "Job successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find_by_id(params["id"])
    @job.destroy
    redirect_to :root, notice: "Job successfully destroyed."
  end

  private

  def job_params
    params.require(:job).permit(:company_name, :job_title, :description, :salary_range, :benefits, :location, :requirements, :to_apply)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def salary_options
    ranges = ["$0-$20,000", "$20,001-$50,000", "$50,001-$100,000", "$100,001-$200,000", "$200,001-$500,000", "$500,001-$1,000,000"]
    ranges.map do |r|
      [r, r]
    end
  end
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
  <div class="field">
    <%= f.label :company_name %></br>
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :job_title %></br>
    <%= f.text_field :job_title %>
  </div>
  <div class="field">
    <%= f.label :location %></br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :salary_range %></br>
    <%= f.select :salary_range, salary_options %>
  </div>
  <div class="field">
    <%= f.label :description %></br>
    <%= f.text_area :description, size: "50x4" %>
  </div>
  <div class="field">
    <%= f.label :benefits %></br>
    <%= f.text_area :benefits, size: "50x4" %>
  </div>
  <div class="field">
    <%= f.label :requirements %></br>
    <%= f.text_area :requirements, size: "50x4" %>
  </div>
  <div class="field">
    <%= f.label :to_apply %></br>
    <%= f.text_area :to_apply, size: "50x4" %>
  </div>
  <div class="field">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Job Listing</h1>

<%= render 'form' %>


<%= link_to 'Destroy', job_path(@job), method: :delete, data: { confirm: 'Are you sure?' } %>
-
<%= link_to "Back to Job Listing", job_path(@job) %>

app/views/jobs/index.html.erb
<h1>Job Listings:</h1>
<%= link_to "New Job Listing", new_job_path %>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th>Company Name</th>
      <th>Job Title</th>
      <th>Location</th>
      <th>Salary Range</th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to job.company_name, job %></td>
        <td><%= job.job_title %></td>
        <td><%= job.location %></td>
        <td><%= job.salary_range %></td>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/jobs/new.html.erb
<h1>New Job Posting</h1>

<%= render 'form' %>

<%= link_to 'Back to Job Listings', root_path %>

app/views/jobs/show.html.erb
<h1><%= @job.company_name %> - <%= @job.job_title %> - <%= @job.location %></h1>

<span><h4>Salary :</h4><%= @job.salary_range %></span>

<h4>Description: </h4>
<p><%= @job.description %></p>

<h4>Benefits:</h4>
<p><%= @job.benefits %></p>

<h4>Requirements:</h4>
<p><%= @job.requirements %></p>

<h4>To Apply:</h4>
<p><%= @job.to_apply %></p>

</br>
<%=link_to "Edit This Job Listing", edit_job_path%>
-
<%=link_to "Back to Job Listings", root_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>W08D03HwJobPosting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
<%= yield %>
</div>
</body>
</html>